python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/6/6checkpoint.pth --e 7 --eval-every 12 --workers 16
fuser -k /dev/nvidia*
python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/7/7checkpoint.pth --e 8 --eval-every 12 --workers 16
fuser -k /dev/nvidia*
python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/8/8checkpoint.pth --e 9 --eval-every 12 --workers 16
fuser -k /dev/nvidia*
python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/9/9checkpoint.pth --e 10 --eval-every 12 --workers 16
fuser -k /dev/nvidia*
python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/10/10checkpoint.pth --e 11 --eval-every 12 --workers 16
fuser -k /dev/nvidia*
python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/11/11checkpoint.pth --e 12 --eval-every 12 --workers 16
fuser -k /dev/nvidia*
python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/12/12checkpoint.pth --e 13 --eval-every 12 --workers 16
fuser -k /dev/nvidia*
python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/13/13checkpoint.pth --e 14 --eval-every 12 --workers 16
fuser -k /dev/nvidia*
python3 -m torch.distributed.launch --nproc_per_node=2 --use_env src/train.py --train-dataset Railway --test-dataset Railway --data-cv 0 --input-size 1333 --model resnet50_mtf_msf_fasterrcnn --mtf iade --msf 4 --warmup --loss bi -b 2 --resume /opt/data/private/zsf/C-3PO/output/resnet50_mtf_msf_fasterrcnn_Railway_0/14/14checkpoint.pth --e 15 --eval-every 12 --workers 16
